version: "3.12"

services:
  mongo:
    image: mongo
    container_name: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: marathonbet
    restart: unless-stopped
    ports:
      - "8000:8000"  # FastAPI
      - "8501:8501"  # Streamlit
    volumes:
      - .:/app
    depends_on:
      - mongo
